### ISSUE TITLE
[ODataRouting] attribute doesn't work if I change "Microsoft.AspNetCore.OData" Version="8.0.0-rc" to stable version.

### ISSUE THREAD

**Issue by prabhdeep-kaur** [xuzhg/MyAspNetCore#11]
Please suggest why it is working with release candidate version only and not with stable versions?

**Comment by xuzhg** [comment]
@prabhdeep-kaur What's the problem when you switch to a stable version? the version number?

**Comment by prabhdeep-kaur** [comment]
When I switch to stable number like 8.0.0 or onwards, as latest stable version is 8.0.6, it doesn't recognize  the attribute in given namespace.
![attribute error](https://user-images.githubusercontent.com/69971332/149889400-f87a2137-76e8-41f2-b0f9-71de62ab5860.PNG)

**Comment by xuzhg** [comment]
@prabhdeep-kaur The ODataRoutingAttribete was renamed as ODataAttributeRoutingAttribute.

You can find details at: https://docs.microsoft.com/en-us/odata/changelog/aspnetcoreodata-8x#800

If you face any other problems, please let me know.  

File new issue https://github.com/OData/AspNetCoreOData/issues/new maybe get more feedbacks from the community.

Or you can send an email to saxu@microsoft.com

**Comment by prabhdeep-kaur** [comment]
I am able to use the attribute now. Thanks for pointing to the right direction. Really appreciated.
