### ISSUE TITLE
[NewQueryOptionIn8] ToLowerInvariant() raises a System.InvalidOperationException

### ISSUE THREAD

**Issue by DSaid** [xuzhg/MyAspNetCore#12]
When using ToLowerInvariant() in the clause expression like in line 45 of NewQueryOptionIn8/NewQueryOptionIn8/Extensions/ProductSaleSearchBinder.cs, I get the following exception :

System.InvalidOperationException: The LINQ expression 'DbSet<XtdText>()
.Where(x => x.Text.ToLowerInvariant().Contains(__txt_0))' could not be translated. Additional information: Translation of method 'string.ToLowerInvariant' failed. If this method can be mapped to your custom function, see https://go.microsoft.com/fwlink/?linkid=2132413 for more information. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.

As a workaround, I changed ToLowerInvariant() to ToLower().

It may be related to the version of Entity Framework we use (I use EF Core).
Any other clue ?

**Comment by xuzhg** [comment]
From the search on the internet, it seems ToLowerInvariant is not supported in EF Core.

**Comment by xuzhg** [comment]
I added the comment into the source codes: 
https://github.com/xuzhg/MyAspNetCore/blob/master/src/NewQueryOptionIn8/NewQueryOptionIn8/Extensions/ProductSaleSearchBinder.cs#L45-L46

Thanks for your information.
