### ISSUE TITLE
The argument 'queryOptionName' is null or empty

### ISSUE THREAD

**Issue by ghost** [xuzhg/MyAspNetCore#13]
When running an odata query, in fact the query in the article : "https://localhost:7260/odata/Shelves?$expand=Books($filter=Id lt 12)", i get an "System.ArgumentException: The argument 'queryOptionName' is null or empty. (Parameter 'queryOptionName')"

![image](https://user-images.githubusercontent.com/56275459/167940249-f10f8f1c-77e3-45c9-a95e-0b606f8719f6.png)

**Comment by xuzhg** [comment]
@josefernandezatceiba I tested it again, it works fine using postman, chrome, edge browser. 

I don't know what could happen in using curl. does it work at your side using other client?

**Comment by ghost** [comment]
You're right, i tried it with insomnia and it worked like a charm. Thanks !! For curl , the url encoding is the issue, testing the endpoint with ""https://localhost:7260/odata/shelves/1/books?%24filter=Id%20eq%2011" worked fine too,
