### ISSUE TITLE
How to make OData case-insensitive?

### ISSUE THREAD

**Issue by garkpit** [xuzhg/MyAspNetCore#8]
How can I make OData work with e.g. $filter=city eq 'London'  (as right now it wants $filter=City eq 'London')  
Javascript is camelCase and not liking this now.

**Comment by xuzhg** [comment]
@garkpit 
If you use model alias, you can let the model builder to build the property name using camel case.

```C#
[DataContract]
public class YouType
{
    [DataMember(Name="city")]
    public string City {get;set;}
}
```

**Comment by HuntJason** [comment]
I believe this is demonstrated within the code. Search for String.Comparison.OrdinalIgnoreCase.

**Comment by garkpit** [comment]
OK, thank you.
Actually it is StringComparison.OrdinalIgnoreCase 
(and you have a typo in the comment! Should say :
// Support case-insensitive
no wonder I had a hard time finding it :)
)
